project:
  type: website
  output-dir: docs
website:
  title: "git-basics"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true



